platform :ios, '10.0'
workspace "Example"
use_frameworks!

target 'Example-iOS' do
  project 'Example.xcodeproj'
  pod 'Just'
end

target 'Example-tvOS' do
  platform :tvos, '10.11'
  project 'Example.xcodeproj'
  pod 'Just'
end

target 'Example-macOS' do
  platform :osx, '10.11'
  project 'Example.xcodeproj'
  pod 'Just'
end

target 'Example-watchOS Extension' do
  platform :watchos, '3.0'

  project 'Example.xcodeproj'
  pod 'Just'
end
